polls/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

pollsProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('user_auth/', include("django.contrib.auth.urls")), 
    path('', include("user_auth.urls")),
    path('polls/', include('polls.urls')),
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name="authenticate_user"),
    path('show_user/', views.show_user, name  = 'show_user'),
    path('register/', views.register_user, name  = 'register'),
    
    
]

polls/models.py
from django.db import models

#Create your models here.

class Question(models. Model):
    question_text = models. CharField(max_length=200)
    pub_date = models. DateTimeField('date published')

class Choice(models.Model):
    question = models. ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models. CharField(max_length=200)
    votes = models. IntegerField(default=0)

def __str__(self):
    return self.question_text,self.choice_text

polls/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Choice, Question

#@login_required(login_url="/user_auth/")
class IndexView(generic.ListView):
    template_name = "polls/poll.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

user_auth/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.http import HttpResponseRedirect


# Create your views here.
def user_login(request): 
    return render(request, 'authentication/login.html')


def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('user_auth:show_user')
        )

def show_user(request):
    print(request.user.username)
    return render(request, 'authentication/user.html', {
        "username": request.user.username,
        "password": request.user.password
    })





    # yourapp/views.py
from django.shortcuts import render, redirect
#from .forms import RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def register_user(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
            
            
            # Create a new user
            #user = User.objects.create_user(username=username, password=password, first_name=first_name)

            # Optionally, you can log in the user after registration
            

    context = {'form': form}
    

    return render(request, 'authentication/register.html', context)

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{{ question.question_text }}</title>
    <style>
        body {
            background-image: url('https://www.nbc.com/generetic/images/nbc-background.png');
            background-size: cover;
            background-position: center;
            display: flex;
            height: 100vh;

        }

        h1 {
            color: rgb(12, 12, 12);
        }

        .card {
            max-width: 600px;
            width: 100%;
            color: rgb(19, 137, 240);
        }

        .btn-primary {
            margin-top: 5px;
            background-color: #007bff;
            border-color: #007bff;
        }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
            cursor: pointer;
        }
    </style>
</head>

<body>

    <div class="card">
        <div class="card-body">
            <h1 class="card-title">{{ question.question_text }}</h1>

            {% if error_message %}
            <div class="alert alert-danger mt-4">
                <strong>{{ error_message }}</strong>
            </div>
            {% endif %}

            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}

                {% for choice in question.choice_set.all %}
                <div class="form-check mt-3">
                    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}"
                        value="{{ choice.id }}">
                    <label class="form-check-label" for="choice{{ forloop.counter }}">
                        {{ choice.choice_text }}
                    </label>
                </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary mt-4">Vote</button>
            </form>
        </div>
    </div>


</body>

</html>

polls/templates/polls/poll.html
{% if latest_question_list %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
            background-image: url('https://www.nbc.com/generetic/images/nbc-background.png');
            background-size: cover;
            justify-content: center;
        }



        .container {


            color: aliceblue;

        }

        h1 {
            color: aliceblue;
        }

        .list-group-item {
            margin-top: 10px;
        }

        .list-group-item a {
            color: rgb(8, 8, 8);

        }

        .list-group-item a:hover {
            color: rgb(22, 156, 173);
        }
    </style>
    <title>Polls Index</title>
</head>

<body>

    <div class="container">
        <h1 class="display-4 text-center">Polls</h1>
        <ul class="list-group">
            {% if user.is_authenticated %}
            {% for question in latest_question_list %}
            <li class="list-group-item">
                <a href="{% url 'polls:detail' question.id %}" class="text-decoration-none">
                    {{ question.question_text }}
                </a>
            </li>
            {% endfor %}
            {% endif %}
        </ul>
    </div>


</body>

</html>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
            background-image: url('https://www.nbc.com/generetic/images/nbc-background.png');
            background-size: cover;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            max-width: 600px;
            margin: 0;
            color: aliceblue;
            text-align: center;
        }

        h1 {
            color: aliceblue;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-top: 10px;
            color: aliceblue;
        }

        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s;
        }

        a:hover {
            color: #0056b3;
        }

        button {
            padding: 10px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
    <title>{{ question.question_text }}</title>
</head>

<body>

    <div class="container">
        <h1 class="display-4">{{ question.question_text }}</h1>

        <ul>
            {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
        </ul>

        <a href="{% url 'polls:detail' question.id %}" class="text-decoration-none">Vote again?</a>
        <a href="{% url 'polls:index' %}"><button>Go Home</button></a>
    </div>


</body>

</html>

user_auth/templates/authentication/login.html
<h1> Login as User </h1>
<form action="{% url 'user_auth:authenticate_user' %}" method="post"> {% csrf_token %}
    <label>Username</label>
    <input type="text" name="username" placeholder="User" required> <br /><br />
    <label>Password</label>
    <input type="password" name="password" required> <br /><br />
    <input type="submit" value="Login" />
</form>

user_auth/templates/authentication/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>

</head>

<body>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
            background-image: url('https://www.nbc.com/generetic/images/nbc-background.png');
            background-size: cover;
            justify-content: center;
        }

        .container {
            max-width: 400px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 8px;
        }

        input {
            padding: 8px;
            margin-bottom: 16px;
        }

        button {
            padding: 10px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            cursor: pointer;
            margin-bottom: 10px;
        }

        button:hover {
            background-color: #45a049;
        }

        .register-link {
            text-align: center;
        }

        .register-link a {
            color: #4caf50;
        }

        .register-link a:hover {
            color: #45a049;
        }

        .input {
            background-color: #35ec3e;
        }
    </style>
    <div class="container">
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <input class="input" type="submit" name="Create User">
        </form>
    </div>
</body>

</html>

user_auth/templates/authentication/user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>

</head>

<body>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            background-image: url('https://www.nbc.com/generetic/images/nbc-background.png');
            background-size: cover;
            justify-content: center;
        }

        .container {
            max-width: fit-content;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 8px;
        }

        input {
            padding: 8px;
            margin-bottom: 16px;
        }

        button {
            padding: 10px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>

    <div class="container">
        <h1>Welcome, {{ username }}</h1>
        <p>Your password is {{ password }} <a href="{% url 'polls:index' %}"><button>Continue to
                    Application</button></a></p>
        {% csrf_token %}
    </div>
</body>

</html>